name = "TestMacroExtensions"
uuid = "ecd20d55-42c1-4d31-a87b-fff5cebab0b6"
authors = ["Ted Papalexopoulos"]
version = "0.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.7"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[targets]
test = ["Logging"]
