name = "PrettyTests"
uuid = "ecd20d55-42c1-4d31-a87b-fff5cebab0b6"
authors = ["Ted Papalexopoulos"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
