name = "PrettyTests"
uuid = "ecd20d55-42c1-4d31-a87b-fff5cebab0b6"
authors = ["Ted Papalexopoulos"]
version = "0.1.0"

[deps]
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.7.0"
Format = "1"